GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/6118c78d036a7b13e02fc80b

###

POST http://localhost:3000/api/genres/
content-type: application/json

{
    "name": "comdey"
}

###

PUT http://localhost:3000/api/genres/6118c8328ba57f543c910767
content-type: application/json

{
    "name": "Comedy"
}

###
DELETE http://localhost:3000/api/genres/6118c8328ba57f543c910767

###

GET http://localhost:3000/api/customers

###

GET http://localhost:3000/api/customers/6118d37b64d7b87814ddfa86

###

POST http://localhost:3000/api/customers/
content-type: application/json

{
    "name": "Amal",
    "isGold": false,
    "phone": "32345"
}

###

PUT http://localhost:3000/api/customers/6118d37b64d7b87814ddfa86
content-type: application/json

{
    "name": "Ajay",
    "isGold": false,
    "phone": "32345"
}

###
DELETE http://localhost:3000/api/customers/6118d37b64d7b87814ddfa86
