
### Genre
GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/6118c76f036a7b13e02fc805

###

POST http://localhost:3000/api/genres/
content-type: application/json

{
    "name": "Sci-fi"
}

###

PUT http://localhost:3000/api/genres/6118c8328ba57f543c910767
content-type: application/json

{
    "name": "Comedy"
}

###
DELETE http://localhost:3000/api/genres/6118c782036a7b13e02fc809

###

### Customer

GET http://localhost:3000/api/customers

###

GET http://localhost:3000/api/customers/6118d37b64d7b87814ddfa86

###

POST http://localhost:3000/api/customers/
content-type: application/json

{
    "name": "Amal",
    "isGold": false,
    "phone": "32345"
}

###

PUT http://localhost:3000/api/customers/6118d37b64d7b87814ddfa86
content-type: application/json

{
    "name": "Ajay",
    "isGold": false,
    "phone": "32345"
}

###
DELETE http://localhost:3000/api/customers/6118d88bf84588794c18a123

### Movie

GET http://localhost:3000/api/movies

###

GET http://localhost:3000/api/movies/611924a884ccb40654414aa8

###

POST http://localhost:3000/api/movies/
content-type: application/json

{
    "title": "Mirror",
    "genreId": "6118c77b036a7b13e02fc807",
    "numberInStock": "10",
    "dailyRentalRate": "5"
}

###

PUT http://localhost:3000/api/movies/611924a884ccb40654414aa8
content-type: application/json

{
    "title": "Terimator 2",
    "genreId": "6118c76f036a7b13e02fc805",
    "numberInStock": "2",
    "dailyRentalRate": "5"
}

###
DELETE http://localhost:3000/api/movies/6119252e6ad59d6df4ffcfb7 

### Rental

GET http://localhost:3000/api/rentals

###

GET http://localhost:3000/api/rentals/611924a884ccb40654414aa8

###

POST http://localhost:3000/api/rentals/
content-type: application/json

{
    "customerId": "61194f165821be1df4185baa",
    "movieId": "61194ef35821be1df4185ba6"
}

###

PUT http://localhost:3000/api/rentals/611924a884ccb40654414aa8
content-type: application/json

{
    "title": "Terimator 2",
    "genreId": "6118c76f036a7b13e02fc805",
    "numberInStock": "2",
    "dailyRentalRate": "5"
}

###
DELETE http://localhost:3000/api/rentals/6119252e6ad59d6df4ffcfb7

### User


GET http://localhost:3000/api/users/me


###

POST http://localhost:3000/api/users/
content-type: application/json

{
    "name": "Anjali",
    "email": "anjali1@gmail.com",
    "password": "12345",
}



### Auth


GET http://localhost:3000/api/auth


###

POST http://localhost:3000/api/auth/
content-type: application/json

{
    "email": "beena@gmail.com",
    "password": "12345"
}