GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/6118c78d036a7b13e02fc80b

###

POST http://localhost:3000/api/genres/
content-type: application/json

{
    "name": "comdey"
}

###

PUT http://localhost:3000/api/genres/6118c8328ba57f543c910767
content-type: application/json

{
    "name": "Comedy"
}

###
DELETE http://localhost:3000/api/genres/6118c8328ba57f543c910767